/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColumnsPopover: typeof import('./src/components/view-controls/ColumnsPopover.vue')['default']
    FilterPopover: typeof import('./src/components/view-controls/FilterPopover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarLink: typeof import('./src/components/SidebarLink.vue')['default']
    SortPopover: typeof import('./src/components/view-controls/SortPopover.vue')['default']
  }
}
